### PR TITLE
NewModule QC Pedigree

### PR DESCRIPTION
**Pull request by RAngelaPG**
Create new module for QCPedigree, add RData for input information that is necessary, add a function for compute the QC, modify "mod_getData" for extract the directory of geno infomation.

### CODE REVIEW

**Comment by covaruber** [comment]
Dear Angela, I tried cloning your repository to test the pedigree module and I found a couple of issues. I uploaded the hap map format but I got an error message saying "genod_data function not found" see attached screenshot. 

Screenshot 2024-02-26 at 11 01 35 AM

If "genod_data" is more of a general function I guess it can go to the cgiarBase. Otherwise let me know where can I find that function.

Also I would suggest you are able to do the cleaning using the sample data included in the application. If that works it should probably be ready to be deployed. Thanks :)

**Comment by covaruber** [comment]
I later assumed the line saying genod_data is a typo and changed it to geno_data so it would run. I still get the message of upload the data in hapmap format. The sample data is already in hapmap format. Why it doesn't work? I tried clicking the load example data, but also using the browse the hapmap file directly. In both cases I still get the message of "please upload your data in hapmap format". Please let me know what else could be missed. Cheers :)

**Comment by RAngelaPG** [comment]
Hi Eduardo,

I don't know which is the problem exactly when I do changes and try to fork many changes are not applied and it moves things that it shouldn't, now I checked and downloaded it and it seems that the folder works without problems.

To carry out this analysis, the genetic information of hybrids and parents is required and in the example hapmap file it only has information on the hybrids, which is why it is not possible to execute the analysis with that data, if is possible to add that information to examples it could work.

These files are a mini example that works
[data.hmp.txt](https://github.com/Breeding-Analytics/bioflow/files/14407547/data.hmp.txt)
[TestParents.csv](https://github.com/Breeding-Analytics/bioflow/files/14407551/TestParents.csv)

Please, let me know if the folder now works.

**Comment by covaruber** [comment]
I have tested Angela and now it works well. I would still recommend to work on the input parameters to understand better how to use them, For example in the first box where it says designation, mother and father and the values are in the order of thousands, you may want to create some "input visuals" that can guide the selection of these values. I would also suggest to put in a hidden setting box the parameters that you really don't want the users to see :) other than that thanks for the contribution, this is a great addition. This week we will discuss how the next modules will be prioritized and hopefully you and Keith can give us a hand onsite of those (like pop structure) :) talk to you later.

**Comment by RAngelaPG** [comment]
Hi Eduardo,

Sure, I need to talk with Keith about the parameters, because for me is dangerous to put all. Also I am working in the pop structure and I almost finish.

Yes, I will change the functions and create the documentation, thank you for remember me.

Best
Angela

**Comment by covaruber** [comment]
Hi Angela, after the Bayer feedback to the tool we had to change a little bit the interface. Please sync the newest changes and see if you can add any graphics to the input tabs to help the users decide the parameters available :) Thanks!

**Pull request merged**
